name: Publish Package to npm
on:
  push:
    branches:
      - experimental
    tags:
      - v*.*.*
      - v*.*.*-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
      - id: pnpm-store-path
        name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - id: version
        uses: VdustR/semver-action@v0
      - name: version
        working-directory: packages/simple-ignore
        run: npm --no-git-tag-version version ${{ steps.version.outputs.version }}
      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          package: packages/simple-ignore
          access: public
